### ISSUE TITLE
Significant results when comparing the same sample

### ISSUE THREAD

**Issue by vferat** [statlab/permute#157] opened 2020-07-02 13:02 UTC
Hey, 

First thanks for all the work you've done to deliver this answome library !

I just noticed a minor issue while using the same sample with `permute.core.one_sample` , 

```
import permute.core
import numpy as np
a = np.random.rand(200)
p_value = permute.core.one_sample(a,a, reps=10000, seed=42, alternative='two-sided')[0]
p_value
0.00019998000199983323
```
For sure means are the same and results should not be significant.

Maybe changing  `>=` to `>` may solve the problem in :
```
hits = np.sum([(tst_fun(z * (1 - 2 * prng.binomial(1, .5, size=n)))) >= tst
                       for i in range(reps)])
```

**Comment by pbstark** [comment] 2020-07-23 17:09
Thank you for your help! This is an issue that's fixed in the "tails" branch, which we have not yet merged into master because of some technical issues in the continuous integration testing.  The >= is correct; the problem is how the two-sided alternative was treated (it assumed the distribution of the test statistic is continuous, but it is discrete). I expect we will be able to merge the tails branch within a few days.

Grateful for your careful reading of the code and your help!

Philip

**Closed by pbstark** 2020-07-23 17:09 UTC
